import { JetBrains_Mono } from "next/font/google";
import Footer from "./Components/Footer/footer";
import Header from "./Components/Header/Header";
import "./globals.css";
import Image from 'next/image';
import gradiantBg from '../../public/images/gradiantBg.jpg';
import { CartProvider } from "../../lib/ContexApi";

const jetBerianMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono"
});

export const metadata = {
  title: "ShopSwift - Spend less, smile more",
  description: "Generated by Md: Jisna",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${jetBerianMono.variable} overflow-scroll flex flex-col antialiased min-h-screen overflow-x-hidden`}>
        <CartProvider>
          <div className="relative flex-grow">
            <div className="absolute inset-0 z-0">
              <Image
                alt="Gradient Background"
                src={gradiantBg}
                placeholder="blur"
                quality={100}
                fill
                sizes="100vw"
                className="object-cover overflow-y-hidden"
              />
            </div>

            <div className="relative z-50">
              <Header />
            </div>

            <div className="relative z-10 m-5 mt-28">
              {children}
            </div>

            <div className="relative z-50">
              <Footer />
            </div>
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
